### ISSUE TITLE
React v18 `npm install` package dependency compatibility

### ISSUE THREAD

**Issue by jason-chen-kiewit** [nutboltu/storybook-addon-mock#104]
Hi there!

My project has recently upgraded to React v18 and I am currently running into a `ERESOLVE unable to resolve dependency tree` error when I try to `npm install storybook-addon-mock`. It does work if I add the `--legacy-peer-deps` flag, but ideally I'd like to avoid using it.

![image](https://user-images.githubusercontent.com/79943064/165395174-a94afd41-cd19-46ea-9360-2c94a2613c8e.png)

Any help would be greatly appreciated!

**Comment by nutboltu** [comment]
@jason-chen-kiewit This issue is fixed in [2.3.2](https://github.com/nutboltu/storybook-addon-mock/releases/tag/2.3.2)

**Comment by jason-chen-kiewit** [comment]
Amazing ty!
