### ISSUE TITLE
bug: Having addon-mock installed breaks pass-through requests

### ISSUE THREAD

**Issue by danielthedifficult** [nutboltu/storybook-addon-mock#114]
Hello team,

I'm having an issue where stories featuring an embedded video player (with Javascript) are not correctly loading.

I've updated to 2.4.1, as I was previously having an issue with the headers not being passed through correctly.

The stories I'm having an issue with do not have the "withMock" decorator imported or used, but other stories (that don't use the player) are using it.

If I comment out all the
```
import withMock from 'storybook-addon-mock';
```
and
```
decorators: [withMock],
```

The video player again works perfectly.

Interesting tidbit: even with the mocking enabled, it works in Safari.

I'm using 1.39.120 Chromium: 102.0.5005.99 (Official Build) (x86_64) 

The 'symptom" is that the player loads forever, it doesn't stop buffering after the first 9 segments, it continues sending network requests for more data... Weird behavior, but probably just a result of something being 'lost in translation' between their library and the server.

**Comment by carloschneider** [comment]
I'm facing some problems after updating to 2.4.1. The `catch` stops working, and I believe that it's related to the headers fix.

**Comment by nutboltu** [comment]
@danielthedifficult can you please share the requests headers for the video player, with and without storybook-addon-mock?

**Comment by nutboltu** [comment]
@carloschneider would you also share the specific case, with a bit more details.

**Comment by danielthedifficult** [comment]
<details>
<summary>Header W/O storybook-addon-mock:</summary>
Main metadata request:

```
:authority: cdnapisec.kaltura.com
:method: POST
:path: /api_v3/service/multirequest
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
content-length: 1312
content-type: application/json
origin: http://localhost:6006
referer: http://localhost:6006/
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: cross-site
sec-gpc: 1
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.99 Safari/537.36
```

Content request:

```
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Connection: keep-alive
Host: cfvod.kaltura.com
Origin: http://localhost:6006
Referer: http://localhost:6006/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
Sec-GPC: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.99 Safari/537.36
```
</details>
<details>
<summary>Header WITH storybook-addon-mock:</summary>

```
:authority: cdnapisec.kaltura.com
:method: POST
:path: /api_v3/service/multirequest
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
content-length: 1312
content-type: application/json
origin: http://localhost:6006
referer: http://localhost:6006/
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: cross-site
sec-gpc: 1
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.99 Safari/537.36
```

Content Request:
```
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Connection: keep-alive
Host: cfvod.kaltura.com
Origin: http://localhost:6006
Referer: http://localhost:6006/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
Sec-GPC: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.99 Safari/537.36
```
</details>

Comparing them locally shows no differences...

**Comment by carloschneider** [comment]
@nutboltu https://github.com/carloschneider/storybook-addon-mock/commit/049e286cf134cc5cc08812d3d8ce25d179bf41f8

The `console.error` in the `catch` doesn't run.

**Comment by danielthedifficult** [comment]
@nutboltu I migrated our stories to use msw's storybook addon, as I didn't want/need the addon 'panel' for changing the responses in realtime, I just wanted to stub/mock simple pre-defined routes. 

Also... it was breaking CI/CD tests that rely on stories rendering properly before pushing code to production 😬 .

msw is successfully mocking the routes I want, and the bypassed routes are working as intended.

Sorry I couldn't help troubleshoot further, but I wanted to let you know that I've resolved this on my end. @carloschneider do you want to keep this open, or should I close?

**Comment by nutboltu** [comment]
@danielthedifficult glad that you sorted out and it's a shame that this package couldn't fix the issue yet. As this package is moving to a major version(V3), I'll allocate some time to look into this issue. I believe @carloschneider has discussed some other issues. @carloschneider would you mind creating another issue if it persists?

I am closing this issue
