### ISSUE TITLE
withMock returning wrong mock when similar url structure

### ISSUE THREAD

**Issue by verissimor** [nutboltu/storybook-addon-mock#127]
I'm trying to mock a server search by user name, which would be used in an autocomplete feature. 

Eg.: `/api/users?name_like=a` returns users starting with **A**; and, `/api/users?name_like=b` returns starting with **B**.

However, mocks always return the last mock when trying to mock this scenario. The panel `Mock Request` also doesn't look good, only displaying the last mock.

![image](https://user-images.githubusercontent.com/2000159/187022757-8d4d5d7e-fc3c-46e9-b85c-012dc46cab64.png)

Here is a piece of code to reproduce:

```typescript
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { useEffect, useState } from 'react';
import withMock from 'storybook-addon-mock';
import { fetch } from '../../Api/fetcher';

const ApiRequestExample = ({ url }: { url: string }) => {
  const [data, setData] = useState();

  useEffect(() => {
    const fetchData = async () => {
      console.log("fetching url: " + url);
      
      setData(await fetch(url));
    };

    fetchData();
  }, []);

  return <><b>{url}</b><pre>{JSON.stringify(data)}</pre></>;
};

export default {
  component: ApiRequestExample,
  title: 'Mock/Missing Mocks',
  decorators: [withMock],
  parameters: {
    mockData: [
      {
        url: '/api/users?name_like=a',
        method: 'GET',
        status: 200,
        response: {
          content: [{ name: 'Allison', age: 32 }, { name: 'Amelia', age: 25 }, { name: 'Amber', age: 19 }], page: 1, size: 3},
      },
      {
        url: '/api/users?name_like=b',
        method: 'GET',
        status: 200,
        response: {
          content: [{ name: 'Betty', age: 22 }, { name: 'Bruce', age: 41 }, { name: 'Bryan', age: 37 }], page: 1, size: 3},
      },
    ],
  },
} as ComponentMeta<typeof ApiRequestExample>;

const Template: ComponentStory<typeof ApiRequestExample> = (prms) => {
  return <ApiRequestExample {...prms} />;
};

export const UsersWithA = Template.bind({});
UsersWithA.args = { url: '/api/users?name_like=a' };

export const UsersWithB = Template.bind({});
UsersWithB.args = { url: '/api/users?name_like=b' };
```

**Comment by RachaneeSaeng** [comment]
I faced the same issue. My workaround was using a custom method for the response so that it gets executed and returns the right data by query parameters.
```
url: '/api/users?name_like=a',
method: 'GET',
status: 200,
response: request => {
    const { searchParams } = request;
    return searchParams.name_like === 'a' ? 'response for a' : 'response for b';
},
```
        
Note: you still need to setup mock for every individual URLs, just the response part that must be changed.

**Comment by nutboltu** [comment]
@verissimor You can use the custom function as @RachaneeSaeng  mentioned above.

**Comment by hayden-homeviews** [comment]
Just came across this issue in my own usage of storybook-addon-mock. I see there's a work-around with using the custom function, but this doesn't feel like intended behaviour. Is it not a bug that different (via query parameter) URLs mocks are effectively negating each-other if they are too similar?
