### ISSUE TITLE
unresolved polished dependency

### ISSUE THREAD

**Issue by stof** [nutboltu/storybook-addon-mock#132]
Registering this addon in storybook triggers an error during the composer build:

```
Module not found: Error: Can't resolve 'polished' in '<redacted>/node_modules/storybook-addon-mock/dist/esm/components/ButtonToggle'
```

It looks like this package is missing a dependency constraint.

**Comment by nutboltu** [comment]
This is fixed in [3.2.0](https://github.com/nutboltu/storybook-addon-mock/releases/tag/3.2.0)
