### ISSUE TITLE
v3 is broken when used with storybook/html

### ISSUE THREAD

**Issue by stof** [nutboltu/storybook-addon-mock#133]
In the v3 of the addon, `withRoundTrip` is registered as a story decorator and uses React hooks internally. This is broken when using `@storybook/html` (and probably also all apps other than `@storybook/react`) because React hooks cannot be called outside a component rendering, and the storybook story function is not invoked in such a context.

The decorator should probably use `addons.getChannel()` and the parameters available in the story context passed to the decorator instead.

**Comment by nutboltu** [comment]
@stof  This is fixed in [3.2.0](https://github.com/nutboltu/storybook-addon-mock/releases/tag/3.2.0)
