### ISSUE TITLE
Addon not working with Storybook 6.5.12 and vue

### ISSUE THREAD

**Issue by leandrogehlen** [nutboltu/storybook-addon-mock#134]
I have created a new project using [@vue/cli](https://cli.vuejs.org/) and: 
- `npx storybook init` 
- `npm i storybook-addon-mock -D`

add storybook-addon-mock addon in.storybook/main.js
```js
module.exports = {
  "stories": [
    "../src/**/*.stories.mdx",
    "../src/**/*.stories.@(js|jsx|ts|tsx)"
  ],
  "addons": [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-interactions",
    "storybook-addon-mock"// if remove this line the error is not happens
  ],
  "framework": "@storybook/vue3",
  "core": {
    "builder": "@storybook/builder-webpack5"
  }
}
```
But the follow erros is happening:

![image](https://user-images.githubusercontent.com/1750751/194386509-97f8410f-dbd4-4101-9b52-ad9c6cae65a9.png)

**Comment by nutboltu** [comment]
@leandrogehlen This is fixed in [3.2.0](https://github.com/nutboltu/storybook-addon-mock/releases/tag/3.2.0)
