### ISSUE TITLE
Undeclared dependency on `prop-types`

### ISSUE THREAD

**Issue by anomiex** [nutboltu/storybook-addon-mock#157]
The package depends on `prop-types` at runtime, but this dependency is not declared.

This happens to work with npm's hoisting since this package is usually used alongside other packages that do declare a dependency on `prop-types`, but will fail in pnpm with hoisting disabled. Possibly also in yarn with p'n'p, although when I tried that I couldn't get it to start working in the first place.

**Comment by nutboltu** [comment]
This issue is fixed in version 4.0.0

**Comment by anomiex** [comment]
This does not appear to be fixed in 4.0.0. Uses of prop-types are still present in the code, and there remains no non-dev dependency on prop-types in your package.json.
