### ISSUE TITLE
String not valid as response

### ISSUE THREAD

**Issue by dread-pirate-johnny-spaceboots** [nutboltu/storybook-addon-mock#162]
I can't set the mock response to be a string. The addons panel reports:

mockData[0] has the following errors
response: "string-value-here" is not valid.

Is there a particular reason it doesn't support strings? They're technically valid JSON and some APIs return plain string values without wrapping them in an object or array.

**Comment by nutboltu** [comment]
@dread-pirate-johnny-spaceboots  you can use the [custom response function](https://storybook-addon-mock.vercel.app/?path=/docs/docs-advanced-setup--docs) to return a string.

We give the flexibility to return any data type with the custom response function.
