### ISSUE TITLE
[bug] Global http requests

### ISSUE THREAD

**Issue by grinsteindavid** [nutboltu/storybook-addon-mock#22]
Hi, whenever I do a http request from a component that does not use this plugin in its story, then the response fails

something like this fails :

const response = await fetch(`${url}?r=${Math.random()}`).then(response => response.blob())

the stack errors said it was faker.js from this module, so I would prefer an option from parameters to enable this instead of being registered globally and preventing http requests to success

**Comment by nutboltu** [comment]
@grinsteindavid do you have any sandbox where you can reproduce the issue? Also It would be great if you share the stack trace as well. :)

**Comment by nutboltu** [comment]
@grinsteindavid My assumption is this issue occurs as the previous version of `storybook-addon-mock` doesn't support **query parameters**. 

You can use the version `1.1.0`. I am closing this issue. If it occurs again then we'll reopen it.
