### ISSUE TITLE
Ambiguous warning message shown on console

### ISSUE THREAD

**Issue by jimmy-leung-coherent** [nutboltu/storybook-addon-mock#37]
Hello. I notice that several warning messages unfortunately come with the application of this addon, and they even appear when the example storybook in this repository is started on my local. They can be reproduced once you 
- clone the repo
- run `yarn && yarn storybook`
- open / reload for `http://localhost:6006/?path=/story/storybook-addon-mock-request--mocking-fetch-and-axios`

![Screenshot 2021-08-12 at 5 27 16 PM](https://user-images.githubusercontent.com/86938380/129173778-a3050c7c-1094-497f-b56b-8773d7dce544.png)
![Screenshot 2021-08-12 at 5 27 30 PM](https://user-images.githubusercontent.com/86938380/129173786-8dddd4e6-ea9a-4575-8ab8-33cbb3b0fda7.png)

It is quite annoying to have them in the development process, even when the mocking works perfectly well. Are there any possible fixes able to come soon?

Anyway thanks for your great work.

**Comment by nutboltu** [comment]
@jimmy-leung-coherent This issue is fixed in version `1.1.0`. Closing this issue.
