### ISSUE TITLE
faker.js URL parsing

### ISSUE THREAD

**Issue by schemata-issimo** [nutboltu/storybook-addon-mock#41]
Hi! Thanks for the quick merge, and I see there's more strictness on valid URLs. The issue being caused now is that hot module reload is sending just chunk.kdas83138rj3.js, rather than the fully qualified http://localhost:6006/chunk.kdas8312.js, which is then going straight into new URL(generated) and being rejected. Everything is working correctly if the withMock decorator is removed. It's also (potentially) a regression from 1.0.0 which allowed url: '/api/v2/xxx' instead of now requiring url: 'http://localhost:6006/api/v2/xxx'. That's not a huge issue of course though as it can be easily resolved locally

I've pasted this into /dist/utils/faker.js and it's working correctly for me with it in place:

```
var withOrigin = rawUrl.indexOf('/') === 0 ? `${window.location.origin}${rawUrl}`
        : rawUrl.indexOf('http') !== 0 ? `${window.location.origin}/${rawUrl}`
        : rawUrl

      var url = new URL(withOrigin);
      var searchParamKeys = [];`
```

**Comment by nutboltu** [comment]
The fix is released in version `1.2.0`
