### ISSUE TITLE
Query parameters

### ISSUE THREAD

**Issue by carloschneider** [nutboltu/storybook-addon-mock#50]
First of all, thanks for your addon.

I'm using your addon for a few days, and I have a scenario where I pass some query parameters based on select options. So depending on what option is selected I'll pass a different parameter to the query string. That way I'll need to set many different items in the `mockData` to the same API url.

I believe that the addon should ignore the query string passed. Or at least have an option to not take the query string passed into account.

**Comment by nutboltu** [comment]
@carloschneider there are some cases where we need to consider the query parameter to distinguish between two separate calls. If we ignore the query string, it will lose the functionality of a specific URL.

In your case, one possible solution would be what you mentioned. You can create multiple `mockData` for multiple query parameters. It's also good to separate the concern.

Any other solution would be welcome  :)

**Comment by jfarris587** [comment]
@nutboltu can there be a solution similar to how cypress handles fixtures? where the url can accept glob patterns at the end, and/or regex to determine a match in the url?

just because some may want different mock data per query param doesn't mean all do.

**Comment by carloschneider** [comment]
An alternative is add a parameter like: `queryString: false` as the same way that you have the `delay` parameter for each request.

**Comment by nutboltu** [comment]
@jfarris587 I might need to look at how cypress handles such a pattern. But any PR is welcome 😃 
@carloschneider `queryString: false` might be an alternative but if we can handle it using regex pattern in the URL that would be more standard way.

**Comment by carloschneider** [comment]
@nutboltu Sorry, I've take a look into the code, and you already check the parameters excluding values, just the keys. I'll close this issue for now. Thank you.
