### ISSUE TITLE
mockData.response presumes a JSON response body

### ISSUE THREAD

**Issue by TravisBernard** [nutboltu/storybook-addon-mock#58]
See here: https://github.com/nutboltu/storybook-addon-mock/blob/e239420f1971a0e1fd5a77ededce4896978d9a91/src/components/RequestItem/index.js#L142

Since response must be either an object or an array it's basically presuming a JSON response body.

That makes it impossible to mock a data stream, SOAP, or other types of APIs that aren't strictly REST+JSON.

Would you be open to accepting a PR to also allow a string type for response so that it can work with a wider range of APIs?

**Comment by midwhite** [comment]
One of my APIs responds a number as body.

![スクリーンショット_2021-11-24_19_55_21](https://user-images.githubusercontent.com/14773605/143225733-1addb64c-9dd6-4fe0-b531-52ec251e9774.png)

This causes following error only in production env:

```
@showPlaceholder(): Expected parameter 'placeholder' either an object or an array
```

![スクリーンショット_2021-11-24_19_57_07](https://user-images.githubusercontent.com/14773605/143225905-5d60cdc9-0c97-499b-a273-445536718347.png)

I hope that values except object or array is allowed as mockData.response 😂

**Comment by nutboltu** [comment]
@midwhite these changes will be released by end of this week. I'll update you accordingly

**Comment by nutboltu** [comment]
@midwhite This issue is addressed in the new major version [2.0.0](https://github.com/nutboltu/storybook-addon-mock/releases/tag/2.0.0).

**Comment by midwhite** [comment]
@nutboltu Thank you for releasing :D

I tried to upgrade to 2.0.0 but I found an following error 😢 
detail: https://github.com/nutboltu/storybook-addon-mock/issues/75

**Comment by nutboltu** [comment]
@midwhite thanks for pointing the issue.  [2.0.1](https://github.com/nutboltu/storybook-addon-mock/releases/tag/2.0.1) has the fixed version.

**Comment by midwhite** [comment]
@nutboltu Thank you for immediate fix :D
I upgraded to v2.0.1 and succeeded in mocking the response body with a number via function like:

```ts
{
  mockData: [
    {
      url: '/news/unread_count',
      method: 'GET',
      status: 200,
      response: () => 100,
    },
  ]
}
```
