### ISSUE TITLE
response.data returned as response.data.data

### ISSUE THREAD

**Issue by DangerStu** [nutboltu/storybook-addon-mock#59]
Great plugin, but I have an issue, here is my mock data:
`mockData: [
    {
      url: 'https://team?search=&detail=light',
      method: 'GET',
      status: 200,
      response: {
        data: [
          {
            id: '7238d186-7cbb-4129-b100-804302ae8c89',
            email: 'Lea.Thompson@gmail.com',
            first_name: 'Lea',
            last_name: 'Thompson'
          },
          {
            id: '577bffd9-88a6-432b-adbe-195ed46ef6f3',
            email: 'Cyndi.Lauper@gmail.com',
            first_name: 'Cyndi',
            last_name: 'Lauper'
          },
          {
            id: 'c47a6c3e-9d9a-4596-b183-68bd4eaf4881',
            email: 'Tom.Cruise@ts.com',
            first_name: 'Tom',
            last_name: 'Cruise'
          }
        ]
      }
    }
  ]`

but it its being returned as response.data.data

**Comment by nutboltu** [comment]
@DangerStu I have used your sample mock data. It appears you are using `axios` and if you look at the [example code](https://github.com/nutboltu/storybook-addon-mock/blob/master/stories/example.stories.js#L89), you will see axios return the response body as `response.data`.
