### ISSUE TITLE
Incompatibility with RTKQ

### ISSUE THREAD

**Issue by ketain** [nutboltu/storybook-addon-mock#60]
I use RTKQ and noticed that response payloads set in storybook-addon-mock are returned as undefined in RTKQ.

I debugged the issue and found that this line in RTKQ is the culprit:
![image](https://user-images.githubusercontent.com/9215393/140484233-00a11218-7b37-4f59-9226-18cb5301a5b3.png)

As you can see, RTKQ assumes the response to be a string, since it is an object it does nothing and returns undefined. 
The obvious solution was then to just stringify my response 
`mockData: [
        {
            url: "myUrl",
            method: "GET",
            status: 200,
            delay: 500,
            response: JSON.stringify(responseObj)
        }
    ]`
    
But storybook-addon-mock doesn't like that. 

Would it be possible to add a flag like "stringifyResponse" which causes the response to be stringified before being sent as response?

**Comment by nutboltu** [comment]
@ketain thanks for raising the issue. I will this feature in the next release.

**Comment by ketain** [comment]
After a bit more debugging I could figure out that, when using storybook-addon-mock the response objects are looking drastically different:
![image](https://user-images.githubusercontent.com/9215393/140702458-f7d19568-9e02-4dbe-bf0a-64b9cdd98720.png)

Usually, sending the same request regularly, it looks like this:
![msedge_Vd2oj1OryW](https://user-images.githubusercontent.com/9215393/140702654-f5d68fb2-2932-4bb3-b8ec-3b20b61590cf.png)

I couldn't figure out why that is though. 

Note, that the standard `text` method of the prototype was overwritten in the response object. Maybe this is the true culprit?  RTKQ expects the method to return a string but instead it gets a promise which resolves to an object?
(Thorugh my debugging efforts I know that the `text` method is used.)

**Comment by nutboltu** [comment]
@ketain looking at the actual response, I can say it returns a ReadableStream instead of JSON format. Currently, this addon only supports JSON as a response.
It's in my pipeline to add these different response time in the future.

**Comment by nutboltu** [comment]
@ketain  In [2.0.0](https://github.com/nutboltu/storybook-addon-mock/releases/tag/2.0.0), We have introduced a new feature where the response can be a function and you can customize your response from the function as below
```js
const Template = (args) => <Component {...args} />;

export const Default = Template.bind({});
Default.parameters = {
    mockData: [
        {
            url: 'https://jsonplaceholder.typicode.com/todos?id=1',
            method: 'GET',
            status: 200,
            response: (request) => {
                const { url, method, body, searchParams } = request;
                return {
                    data:  new ReadableStream()
                }
            },
        },
    ],
};
```

**Comment by shedali** [comment]
@ketain did you manage to get this to work? I have not been able to get this addon to work with RTQ despite using the new return function
