### ISSUE TITLE
Problem with mock change and play/pause button

### ISSUE THREAD

**Issue by carloschneider** [nutboltu/storybook-addon-mock#62]
I was facing a problem with mock change on storybook page ("mock request" addon tab), then digging into the code I've found this:

In this file the parameters are passed separated.

https://github.com/nutboltu/storybook-addon-mock/blob/e239420f1971a0e1fd5a77ededce4896978d9a91/src/manager.js#L21-L27

And here the parameters are received in the same way.

https://github.com/nutboltu/storybook-addon-mock/blob/e239420f1971a0e1fd5a77ededce4896978d9a91/src/index.js#L19-L22

But debugging I realized that the `channel.on` receive only one parameter. I guess this behavior maybe occur only in my storybook version: `5.3.19`. Locally I've change those files and worked well:

`/src/manager.js`
```js
    const onSkip = (item) => {
        emit(ADDONS_MOCK_UPDATE_DATA, {
            item,
            key: 'skip',
            value: !item.skip,
        });
    };

    const onRequestChange = (item, key, value) => {
        emit(ADDONS_MOCK_UPDATE_DATA, {
            item,
            key,
            value,
        });
    };
```

`/src/index.js`
```js
        channel.on(ADDONS_MOCK_UPDATE_DATA, ({ item, key, value }) => {
            faker.update(item, key, value);
            channel.emit(ADDONS_MOCK_SEND_DATA, faker.getRequests());
        });
```

My concern is my changes affect others storybook versions.

**Comment by nutboltu** [comment]
@carloschneider as you raised a PR for this issue, can you please also check if your changes work for storybook v6

**Comment by carloschneider** [comment]
@nutboltu could you share the source code of GH Page?

**Comment by carloschneider** [comment]
@nutboltu sorry, my bad, I've run `yarn storybook` locally and works perfectly. Do you want me to change the package version?

**Comment by nutboltu** [comment]
It would be great if you can check the other version. But it's optional. Let me know what you prefers.

**Comment by carloschneider** [comment]
@nutboltu I've checked both versions 5 and 6. Version 5 is running on my project. To test with version 6 I've run `yarn storybook` in the addon repository. Works fine in both versions.

My question above is about the package version, should I bump the version in my PR?

**Comment by nutboltu** [comment]
@carloschneider Let's keep the version as it was before. I was asking to check both versions which you have covered.

**Comment by carloschneider** [comment]
@nutboltu thank you, I'll be waiting for the release.

**Comment by nutboltu** [comment]
@carloschneider the change reflects on version `1.7.0`
