### ISSUE TITLE
`requestPath matched false`

### ISSUE THREAD

**Issue by Myzel394** [nutboltu/storybook-addon-mock#86]
Using this configuration:

```javascript
WithoutSession.parameters = {
	mockData: [
		{
			url: "http://localhost:6006/api/auth/session",
			method: "GET",
			status: 200,
			response: {},
		},
		{
			url: "localhost:6006/api/auth/session",
			method: "GET",
			status: 200,
			response: {},
		},
        ]
}
```

I always get this error:

![image](https://user-images.githubusercontent.com/50424412/150002461-df606ae2-bd36-44e6-87bf-00c2ae7c5fa9.png)

The requests don't get mocked and are sent out

Seems like the urls are not mocked correctly

**Comment by nutboltu** [comment]
@Myzel394 looking at the second url, it's not a valid url. and considering the first url, can use just use the relative path?

**Comment by nutboltu** [comment]
Closing this ticket as this is stale for a while.
