### ISSUE TITLE
Response text() returns object instead of text

### ISSUE THREAD

**Issue by mchill** [nutboltu/storybook-addon-mock#89]
### Description

I'm having an issue with the faked response type. Specifically, the `text()` and `json()` methods both return the response object, when [Response.text()](https://developer.mozilla.org/en-US/docs/Web/API/Response/text) should return a string to be compliant with the API.

This is a problem when using this library with RTK Query, for example. For some reason, they read the `text()` response and parse it to JSON themselves instead of calling `json()` directly. Can't say I get why, but it's technically valid.
https://github.com/reduxjs/redux-toolkit/blob/master/packages/toolkit/src/query/fetchBaseQuery.ts#L57

I assume there are also other libraries out there that read responses in the same way. This is just the one that I happened to run into.

### Proposed Solution

The problem is created by this line.
https://github.com/nutboltu/storybook-addon-mock/blob/master/src/utils/response.js#L13

Calling the 3rd argument `responseText` seems to be misleading, since as far as I can tell it will always be an object. Just to be careful, though, I believe that the code should be:
```javascript
this.text = () => Promise.resolve(typeof responseText === "string" ? responseText : JSON.stringify(responseText));
this.json = () => Promise.resolve(responseText);
```

Let me know if you agree on the solution and I can open up a quick PR.

**Comment by nutboltu** [comment]
@mchill Thanks for the solution. just a short note, as Response.text() always returns a [string](https://developer.mozilla.org/en-US/docs/Web/API/Response/text#return_value) , we can directly return the JSON.stringify.

```js
this.text = () => Promise.resolve(JSON.stringify(responseText));
this.json = () => Promise.resolve(responseText);
```
Please feel free to raise a PR. 😄 
```
