### ISSUE TITLE
Unexpected console output

### ISSUE THREAD

**Issue by edoroshenko** [nutboltu/storybook-addon-mock#94]
The package unconditionally outputs the following:
```
console.log
      this.requestMap[key] {
        url: '...',
        response: { ... },
        ignoreParams: true,
        path: '...',
        searchParamKeys: [],
        method: 'GET',
        status: 200,
        delay: 0,
        skip: false
      } key ...

      at Faker.matchMock (node_modules/storybook-addon-mock/dist/utils/faker.js:104:17)

    console.log
      requestPath ... matched false

      at Faker.matchMock (node_modules/storybook-addon-mock/dist/utils/faker.js:105:17)
```
The package downloaded from the `npm` contains the following code:
```
        console.log('this.requestMap[key]', _this.requestMap[key], 'key', key);
        console.log('requestPath', requestPath, 'matched', (0, _pathToRegexp.match)(requestPath)(path));
```

I've checked the source code, there's no output there. I've cloned the repo and built it locally, there's no output as well.
Did it appear by mistake, or for a purpose?
Thanks in advance.

**Comment by nutboltu** [comment]
@edoroshenko can you please share which version have you used?

**Comment by mz921** [comment]
I used 2.1.0 and have the same problem.

**Comment by edoroshenko** [comment]
I used the same

**Comment by nutboltu** [comment]
`2.1.0` is a faulty version and is already marked as deprecated. Please upgrade to `2.3.0` the latest version. This console log is removed.
