### ISSUE TITLE
Wrong package published for 2.1.0

### ISSUE THREAD

**Issue by dingjules** [nutboltu/storybook-addon-mock#95]
Hey, it seems that the 2.1.0 package is the same as 2.0.2. Is there any chance that the wrong package was published?

According to this tool, the only difference between these two versions is the version bump.
https://diff.intrinsic.com/storybook-addon-mock/2.0.2/2.1.0

**Comment by nutboltu** [comment]
@dingjules I have marked version 2.1.0 as deprecated and released 2.3.0 with the latest changes.

https://diff.intrinsic.com/storybook-addon-mock/2.0.2/2.3.0

Thanks for pointing this out. really appreciate it.
